# Generated by Django 6.0.2 on 2026-02-27 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_me', '0002_blog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
