# Generated by Django 6.0.2 on 2026-02-28 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_me', '0003_alter_category_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='auther',
            new_name='author',
        ),
    ]
