# Generated by Django 6.0.2 on 2026-02-28 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_me', '0005_alter_blog_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Published', 'Published')], max_length=20),
        ),
    ]
