# Generated by Django 6.0.2 on 2026-02-28 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_me', '0008_alter_blog_blog_body_alter_blog_short_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
