# Generated by Django 6.0.2 on 2026-03-03 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_me', '0011_sociallinks_remove_abouts_profile_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sociallinks',
            options={'verbose_name_plural': 'SocialLinks'},
        ),
    ]
