# Generated by Django 6.0.2 on 2026-03-03 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_me', '0012_alter_sociallinks_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
