# Generated by Django 6.0.2 on 2026-03-03 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_me', '0013_category_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
    ]
